config/routes.rb
SciencegamereviewsOrg::Application.routes.draw do

  constraints host: 'sciencegamecenter.org' do
    get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
  end

  root :to => 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'
  get '/review', to: 'static_pages#review'
  get '/jam', to: 'static_pages#jam'
  get '/forum_approval', to: 'static_pages#forum_approval'
  get '/robots.txt', to: 'static_pages#robots'

  resources :users do
    member do
      get 'resend_parent_email'
      get 'confirm_child_account'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :games do
    resources :screenshots, shallow: true
  end
  resources :subjects, only: :index
  resources :platforms, only: :index
  resources :player_reviews
  resources :comments
  resources :blog_posts

  resources :stats, only: :index

  post "versions/:id/revert" => "versions#revert", as: 'revert_version'

  get '/signup',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  delete '/logout',  to: 'sessions#destroy'

  get '/sso/discourse', to: 'sso#discourse'











end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    get_pinned_blog_posts
    get_page_of_blog_posts(exclude_pinned: params[:topic].blank?)
  end

  def about
  end

  def contact
  end

  def privacy
  end

  def review
  end

  def jam
    # If there's a Game Jam blog post, redirect to it instead of using the hardcoded content.
    blog_post = BlogPost.published.where(use_as_game_jam_page: true).reorder(published_at: :desc).first
    if blog_post
      redirect_to blog_post
    end
  end

  def forum_approval
    unless current_user && current_user.needs_forum_approval?
      redirect_to root_path
    end
  end

  def robots
  	if Rails.env.production? && request.host.include?("www.sciencegamecenter.org")
	  	filename = "config/robots.production.txt"
	  else
  		filename = "config/robots.development.txt"
  	end
  	robots = File.read(Rails.root + filename)
  	render text: robots, layout: false, content_type: 'text/plain'
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1 class="left">About the <strong>Science Game Center</strong></h1>
<p>
	The goal of the <strong>Science Game Center</strong> is to demonstrate to teachers, scientists, museums, and parents the myriad ways games can be used to improve education in math and science.  The <strong>Science Game Center</strong> will provide a place where users can describe their experiences with math and science games, gather information on game strengths and weaknesses, and share tips on how to use games to help students reach their educational goals.</p>
<p>
	The <strong>Science Game Center</strong> provides</p>

<ul>
<li>
	a curated List of Science Games searchable by platform and by curated list of concepts</li>
<li>
	public reviews for each game with 5 star ratings for Fun, Science, and Teaching Effectiveness</li>
<li>
	ability to search for reviews by Teachers, Scientists, or by age of reviewer</li>
<li>
	long form authoritative discussion by SGC expert, teacher and scientist for each game</li>
</ul>
<br />
<h2>
	How it works</h2>
<p>
	Any <strong>Science Game Center</strong> user <%= link_to 'can write an "Amazon style" review, with three 5-point ratings for Fun, Learning, and Science', review_path %>.  Additionally, the SGC team will vet teachers and scientists and provide them appropriate user profiles.  Students under 13, with their parent&rsquo;s permission, can review games, too.  All reviews will be searchable by age of the reviewer, and by reviewers&rsquo; area of expertise.  A central location for information on many games and with many types of reviewers, the <strong>Science Game Center</strong> will also increase the audience for each game.  A 5<sup>th</sup> grade teacher can find a game that is intended for AP biology students, reported by scientists to teach basic cell biology, has been used by other 5<sup>th</sup> grade teachers, and favorably reviewed by 5<sup>th</sup> grade players. </p>
<br />
<h2>
	Analysis and Critical Review</h2>
<p>
	The SGC team intends to build the <strong>Science Game Center</strong> into a center for analysis of learning games.  Each game&rsquo;s page will have three longer, authoritative reviews: one each by the SGC team, a teacher and a scientist in the field.  The SGC team, collaborating teachers and scientists will write reviews of games in each field, drawing on the information we collect through discussion with experts gathered at meetings held by the SGC team.  The <strong>Science Game Center</strong> will provide critical analyses of game functionality, something the learning technology field is missing.  Good reviews and helpful analyses by the SGC team and collaborators can be added to the evaluation section of grant reports.  Rewarding developers for high quality games will raise awareness and appreciation for quality learning games.</p>

<hr />

<p><strong>www.ScienceGameCenter.org</strong> is brought to you by Molecular Jig Games and several volunteers.  If you would like to volunteer, please <%= link_to "contact us", contact_path %>. We also accept advertising for science-related ads. Contact <a href="mailto:admins@sciencegameceter.org">admins@sciencegameceter.org</a>.</p>

<p><strong>Melanie Stegman, Ph.D.</strong><br />
Director, Science Game Center<br />
Owner, <a href="http://www.molecularjig.com/">Molecular Jig Games</a></p>

<p><strong>Andy Hall</strong><br />
Curator, Science Game Center<br />
Owner, <a href="http://www.testtubegames.com/">Test Tube Games</a></p>

<p><strong>Adam Stegman</strong><br />
Curator, Science Game Center<br />
IT and English Teacher, <a href="http://teacherweb.com/OH/OLL/MrStegman">Our Lady of Lourdes School</a></p>

<p><strong>John Pray</strong><br />
Web Developer, Science Game Center<br />
<a href="https://github.com/LouieGeetoo">GitHub profile</a></p>

<p><strong>David Orloff</strong><br />
Social Outreach, Science Game Center</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>

<h1 class="left">Contact Us</h1>
<h3>Are you a teacher or scientist who'd like to write an Expert Review for us? A player or developer with a game you'd like us to feature? Do you have another comment, question, or suggestion?</h3>
<p>Email the team at <b><a href="mailto:<%= ENV['ADMINS_EMAIL'] %>"><%= ENV['ADMINS_EMAIL'] %></a></b>, or contact</p>
<p><b>Dr. Melanie Stegman</b><br />
	Director of the Science Game Center<br />
	Email: <a href="mailto:melanie.stegman@gmail.com">melanie.stegman@gmail.com</a><br />
</p>
<p>We look forward to hearing from you!</p>

app/views/static_pages/forum_approval.html.erb
<% provide(:title, 'Request Forum Approval') %>

<h1 class="left">Request Forum Approval</h1>
<h3>You're close to posting on the Science Game Center forum!</h3>
<p>Since you're under thirteen and you created your account before the forum opened, your parent/guardian needs to specifically approve your forum access.</p>
<p>Click this button to send an email to your parent/guardian at <b><%= current_user.parent_email %></b> with a link for them to re-approve you:</p>

<p><%= link_to "Request forum approval", resend_parent_email_user_path(current_user), :class => "btn btn-large btn-primary" %></p>

<p>If you need to update your parent/guardian's email address, <%= link_to "do so here", edit_user_path(current_user) %>.</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Video games that teach science') %>

<div class="blog_posts" style="margin-top: -10px;">
  <%= render partial: 'blog_posts/pinned_and_unpinned_posts' %>
</div>

<%= will_paginate(@blog_posts, params: { controller: :blog_posts, action: :index }) %>

<% if admin? %>
  <p><%= link_to "New blog post", new_blog_post_path, class: 'btn btn-info'  %></p>
  <br />
<% end %>

app/views/static_pages/jam.html.erb
<% provide(:title, 'Science Game Jam') %>

<h1 class="left">
  <%= image_tag "jam-2022-logo.png", alt: "Science Game Jam - September 10-18, 2022", style: "max-width: 90%; margin: -10px -20px;" %>
</h1>

<p>
  Register here: <a href="https://forms.gle/JbBhXRkBkt5jAkPK6">Science Game Jam Sign Up</a>
</p>

<p>
  Scientists dream of worlds too big, too small, or too complex to explain. During Science Game Jam, game developers will rise to the challenge of creating games in those worlds, in collaboration with scientists.
</p>

<p>
  Science Game Jam is 9 days of guided interaction between scientists and a team of game developers (designers, programmers, artists, writers, sound designers). Science Game Jam differs from most game jams in two ways. First, we are pairing experienced game jammers with scientists who are post doctorate level or higher.  Second, the jam has a required schedule and a suggested game design process. These differences are designed to spur novel game mechanics out of natural world phenomena.
</p>

<h2>
  Why is it happening?
</h2>

<p>
  Doing science is fun, even though learning science can be overwhelming. Games make learning fun, but game development can be overwhelming! Science Game Jam is a workshop where game developers learn how to make more exciting games about science and where scientists learn the game development process. Through games, players have learned how to eradicate a zombie horde many times over, but few have been taught how the body kills a virus. Science Game Jam is our experiment to mix these disparate elements with aims to create novel and compelling games that take place in this universe.
<p>

<h2>
  Where is the jam?
</h2>

<p>
  Science Game Jam is held entirely online through a moderated <a href="https://discord.gg/D52S6KQ6au">Discord server called Science Game Jam</a> for participants. Upon completion of the jam, games will be listed on ScienceGamesCenter.org for all to play, rate, and enjoy.  To ensure your game is found, use #SGJ22 when hosting it on itch.io or your preferred hosting solution.  Winners will be determined by searching #SGJ22 on ScienceGamesCenter.org and sorting by highest rank.
<p>

<h2>
  When will I need to be online?
</h2>

<p>
  All scientists and game developers must attend the meetings in the image below.  Only prolonged interaction of scientists and game developer teams will allow the iterative development process required to design an engaging experience.  Additionally, you must playtest and watch others playtest to be sure that what you and you team managed to create does not seem to impart any misconceptions. Participants and playtesters are especially encouraged to attend the Saturday playtesting session!
</p>

<figure style="margin-left: 0; margin-right: 0;">
  <%= image_tag "jam-2022-calendar.png", alt: "A calendar showing the same dates listed below.", style: "max-width: 500px; width: 100%;" %>
  <figcaption>Fig. 1. Scientists and teammates must agree to attend these sessions.</figcaption>
</figure>

<p>
  Science Game Jam will run from 10 September 1:00 PM EDT, 2022 to 18 September 6:00 PM EDT, 2022.  Scientists and Developers are required to attend (All times are Washington, DC times):
</p>

<ul>
  <li>Saturday 9/10, 1pm - 7pm</li>
  <li>Monday 9/12, 6-7pm</li>
  <li>Wednesday 9/14, 6-7pm</li>
  <li>Saturday 9/17, 1pm - 4pm</li>
</ul>

<p>
  Sunday is the deadline to get your game listed on <a href="https://sciencegamecenter.org">ScienceGameCenter.org</a>.  Listed games will need a link to where they can be played online, or downloaded and played.  We suggest <a href="https://itch.io/">Itch.io</a> as a lovely indie game site to host your game.  We welcome board games as printable downloads as well!  Use #SGJ2022 everywhere.
</p>

<h2>
  Who&rsquo;s organizing it?
</h2>

<p>
  The jam is being organized by the <a href="https://www.facebook.com/groups/115048675174689">Washington, DC chapter of the International Game Developer Association (IGDA</a>), which is composed of a diverse selection of game developers.
  <br /><br />
  Contact person: <a href="https://www.sciencegamecenter.org/contact">Melanie Stegman, Ph.D.</a>
</p>

<h2>
  FAQ
</h2>

<p>
  Check out our Q&amp;A <a href="https://docs.google.com/document/d/15rZXnTBLIzTStpxD6Dw7RBd-QCq3PdbPF02iMnD-wGY/edit?usp=sharing">here</a>.
</p>

<br /><br />

<style>
  h2 {
    margin-top: 2rem;
  }
</style>

app/views/static_pages/privacy.html.erb
<% provide(:title, 'Terms and Privacy') %>

<h1 class="left">Terms and Privacy</h1>

<div id="terms_and_conditions">
<h2>
	Web Site Terms and Conditions of Use
</h2>

<h3>
	1. Terms
</h3>

<p>
	By accessing this web site, you are agreeing to be bound by these 
	web site Terms and Conditions of Use, all applicable laws and regulations, 
	and agree that you are responsible for compliance with any applicable local 
	laws. If you do not agree with any of these terms, you are prohibited from 
	using or accessing this site. The materials contained in this web site are 
	protected by applicable copyright and trade mark law.
</p>

<h3>
	2. Use License
</h3>

<ol type="a">
	<li>
		Permission is granted to temporarily download one copy of the materials 
		(information or software) on The Science Game Center's web site for personal, 
		non-commercial transitory viewing only. This is the grant of a license, 
		not a transfer of title, and under this license you may not:
		
		<ol type="i">
			<li>modify or copy the materials;</li>
			<li>use the materials for any commercial purpose;</li>
			<li>attempt to decompile or reverse engineer any software contained on The Science Game Center's web site;</li>
			<li>remove any copyright or other proprietary notations from the materials; or</li>
			<li>transfer the materials to another person or "mirror" the materials on any other server.</li>
		</ol>
	</li>
	<li>
		This license shall automatically terminate if you violate any of these restrictions and may be terminated by The Science Game Center at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
	</li>
</ol>

<h3>
	3. Disclaimer
</h3>

<ol type="a">
	<li>
		The materials on The Science Game Center's web site are provided "as is". The Science Game Center makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, The Science Game Center does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
	</li>
</ol>

<h3>
	4. Limitations
</h3>

<p>
	In no event shall The Science Game Center or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on The Science Game Center's Internet site, even if The Science Game Center or a The Science Game Center authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
</p>
			
<h3>
	5. Revisions and Errata
</h3>

<p>
	The materials appearing on The Science Game Center's web site could include technical, typographical, or photographic errors. The Science Game Center does not warrant that any of the materials on its web site are accurate, complete, or current. The Science Game Center may make changes to the materials contained on its web site at any time without notice. The Science Game Center does not, however, make any commitment to update the materials.
</p>

<h3>
	6. Links
</h3>

<p>
	The Science Game Center has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by The Science Game Center of the site. Use of any such linked web site is at the user's own risk.
</p>

<h3>
	7. Site Terms of Use Modifications
</h3>

<p>
	The Science Game Center may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
</p>

<h3>
	8. Governing Law
</h3>

<p>
	Any claim relating to The Science Game Center's web site shall be governed by the laws of the District of Columbia without regard to its conflict of law provisions.
</p>

<p>
	General Terms and Conditions applicable to Use of a Web Site.
</p>
</div>

<div id="privacy_policy">
<h2>
	Privacy Policy
</h2>

<p>
	Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
</p>

<ul>
	<li>
		Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
	</li>
	<li>
		We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.		
	</li>
	<li>
		We will only retain personal information as long as necessary for the fulfillment of those purposes. 
	</li>
	<li>
		We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. 
	</li>
	<li>
		Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date. 
	</li>
	<li>
		We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
	</li>
	<li>
		We will make readily available to customers information about our policies and practices relating to the management of personal information. 
	</li>
</ul>

<p>
	We are committed to conducting our organization in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. 
</p>
</div>

<hr />
<p>Please direct any questions to <a href="mailto:<%= ENV['ADMINS_EMAIL'] %>"><%= ENV['ADMINS_EMAIL'] %></a> or <a href="http://www.molecularjig.com/">Molecular Jig Games</a>.