config/routes.rb
SciencegamereviewsOrg::Application.routes.draw do

  constraints host: 'sciencegamecenter.org' do
    get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
  end

  root :to => 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'
  get '/review', to: 'static_pages#review'
  get '/jam', to: 'static_pages#jam'
  get '/forum_approval', to: 'static_pages#forum_approval'
  get '/robots.txt', to: 'static_pages#robots'

  resources :users do
    member do
      get 'resend_parent_email'
      get 'confirm_child_account'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :games do
    resources :screenshots, shallow: true
  end
  resources :subjects, only: :index
  resources :platforms, only: :index
  resources :player_reviews
  resources :comments
  resources :blog_posts

  resources :stats, only: :index

  post "versions/:id/revert" => "versions#revert", as: 'revert_version'

  get '/signup',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  delete '/logout',  to: 'sessions#destroy'

  get '/sso/discourse', to: 'sso#discourse'











end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :commentable_id, :commentable_type, :content, :status

  default_scope { order(created_at: :asc) }

  belongs_to :commentable, polymorphic: true
  belongs_to :user

  has_paper_trail

  validates :content, presence: true
  validates :commentable_id, presence: true
  validates :commentable_type, presence: true

  def approved?
  	self.status == 'Approved'
  end

  def approve!
  	self.update_attribute(:status, 'Approved')
  end

  def pending?
  	self.status == 'Pending' || self.status.nil?
  end

  def make_pending!
  	self.update_attribute(:status, 'Pending')
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_filter :signed_in_user,  only: [:create, :edit, :update, :destroy]
	before_filter :correct_user,    only: [:edit, :update, :destroy]

  def create
    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    if @comment.save
      if current_user.is_admin?
        @comment.approve!
        flash[:success] = "Comment created and published."
      else
        @comment.make_pending!
        CommentMailer.notify_for_approval(@comment).deliver_now
        flash[:success] = "Your comment has been submitted and will show up on the site once it is approved. Thank you!"
      end
      redirect_to @comment.commentable
    else
    	@player_review = @comment.commentable
    	render "#{@comment.commentable_type.underscore.pluralize}/show"
    end
  end

  def edit
  end

  def update
    if @comment.update_attributes(params[:comment])
      if current_user.is_admin?
        @comment.approve!
        flash[:success] = "Comment updated."
      else
        @comment.make_pending!
        CommentMailer.notify_for_approval(@comment).deliver_now
        flash[:success] = "Your revised comment has been submitted and will show up on the site once it is approved. Thank you!"
      end
      redirect_to @comment.commentable
    else
      render 'edit'
    end
  end

  def destroy
  	comment = Comment.find(params[:id])
    Comment.find(params[:id]).destroy
    flash[:success] = "Comment destroyed now and forever."
    redirect_to comment.commentable
  end

  private
    def correct_user
      @comment = Comment.find(params[:id])
      redirect_to(root_path) unless current_user?(@comment.user) || current_user.is_admin?
    end
end

app/views/comments/_comment.html.erb
<div class="comment row">
	<div class="span1">
		<%= avatar_for comment.user, size: 60 %>
	</div>
	<div class="span9">
		<p class="comment_user"><b><%= comment.user ? comment.user.name : "Someone" %></b> on <%= comment.created_at.to_formatted_s(:long) %> said
			<% if signed_in? && (current_user?(comment.user) || admin?) %>
			<b><i> -
				<%= link_to "Edit comment", edit_comment_path(comment) %>,
				<%= link_to "Delete comment", comment, method: :delete, data: { confirm: "Are you sure you want to destroy this comment now and for the rest of time, with no going back?" } %>
			</i></b>
		<% end %>
		</p>
		<% if (current_user?(comment.user) || admin?) && comment.pending? %>
			<div class="alert">
				<strong>Pending.</strong> This comment is awaiting administrator approval before it appears to other site visitors.
			</div>
		<% end %>
		<div>
			<%= markdown comment.content %>
		</div>
		<hr />
	</div>
</div>

app/views/comments/_comments.html.erb
<% if commentable.comments.count < 1 %>
	<p>There are no comments on this review.</p>
<% else %>
	<% commentable.comments.each do |c| %>
		<%= render 'comments/comment', comment: c %>
	<% end %>
<% end %>

<h3>Leave a comment</h3>
<% if !signed_in? %>
	<p><%= link_to "Sign up", signup_path %> or <%= link_to "log in", login_path %> to leave a comment.</p>
<% else %>

	<%= avatar_for @current_user %>
  <p>
    <b><%= @current_user.name %></b><br />
    <%= Time.zone.now.to_formatted_s(:long) %>
	</p>

	<%= form_for comment do |f| %>

	  <%= render 'shared/error_messages', object: f.object %>

	  <%= f.text_area :content, rows: 5 %>
	  <p class="form-help">Format using HTML tags or <a href="http://daringfireball.net/projects/markdown/basics" target="_blank">Markdown</a>: **bold** _italics_ [link](http://example.com)</p>

	  <%= f.hidden_field :commentable_id, value: commentable.id %>
	  <%= f.hidden_field :commentable_type, value: commentable.class.name %>

	  <p class="form-help" id="submit-help">After submitting, a site administrator will need to approve your comment before it shows up. We're usually pretty prompt about it.</p>
	  <%= f.submit "Submit comment", :class => "btn btn-large btn-primary" %>
	<% end %>

<% end %>

app/views/comments/edit.html.erb
<% provide(:title, 'Editing a comment') %>

<h1 class="left">Editing a comment</h1>

<% if @comment.user %>
	<div class="user_info">
		<%= avatar_for @comment.user %>
		<h3>by <%= @comment.user.name %></h3>
		<% if @current_user.is_admin? %>
		<p>Email this user: <%= link_to @comment.user.email, @comment.user.email %></p>
		<% end %>
	</div>
<% else %>
	<h2>by a user that has since been deleted</h2>
<% end %>

<%= form_for @comment do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.text_area :content, rows: 10 %>
  <p class="form-help">Format using HTML tags or <a href="http://daringfireball.net/projects/markdown/basics" target="_blank">Markdown</a>: **bold** _italics_ [link](http://example.com)</p>

  <% if @current_user.is_admin? %>
  <%= f.label :status, "Approval status" %>
  <%= f.select :status, ["Pending", "Approved"] %>
  <p class="form-help">Whether this review appears to the public. Only administrators can change this value.</p>
  <% end %>

  <p class="form-help" id="submit-help">After submitting, a site administrator will need to approve your comment before it shows up. We're usually pretty prompt about it.</p>
  <%= f.submit "Submit comment", :class => "btn btn-large btn-primary" %>
<% end %>