config/routes.rb
SciencegamereviewsOrg::Application.routes.draw do

  constraints host: 'sciencegamecenter.org' do
    get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
  end

  root :to => 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'
  get '/review', to: 'static_pages#review'
  get '/jam', to: 'static_pages#jam'
  get '/forum_approval', to: 'static_pages#forum_approval'
  get '/robots.txt', to: 'static_pages#robots'

  resources :users do
    member do
      get 'resend_parent_email'
      get 'confirm_child_account'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :games do
    resources :screenshots, shallow: true
  end
  resources :subjects, only: :index
  resources :platforms, only: :index
  resources :player_reviews
  resources :comments
  resources :blog_posts

  resources :stats, only: :index

  post "versions/:id/revert" => "versions#revert", as: 'revert_version'

  get '/signup',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  delete '/logout',  to: 'sessions#destroy'

  get '/sso/discourse', to: 'sso#discourse'











end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :title, :content, :published_at, :pinned, :topic_list, :use_as_game_jam_page

  scope :published, -> { where("published_at <= ?", Time.now).order(published_at: :desc) }

  validates :title, presence: true

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  acts_as_taggable_on :topics

  has_paper_trail

  def published_at_string
    if published_at.blank?
      "Unpublished"
    else

      if published_at.future?
        datetime_string = published_at.
          in_time_zone('Eastern Time (US & Canada)').
          strftime('%B %-d, %Y at %-l:%M %p %Z')

        "Will publish on #{datetime_string}"

      else
        datetime_string = published_at.
          in_time_zone('Eastern Time (US & Canada)').
          strftime('%B %-d, %Y')

        datetime_string
      end
    end
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_filter :signed_in_user,  except: [:index, :show]
  before_filter :admin_user,      except: [:index, :show]

  def index
    get_pinned_blog_posts
    get_page_of_blog_posts(exclude_pinned: params[:topic].blank?)
  end

  def show
    find_blog_post
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    fix_published_at_timezone
    @blog_post = BlogPost.new(params[:blog_post])
    if @blog_post.save
      flash[:success] = "Blog Post created."
      redirect_to @blog_post
    else
      render :new
    end
  end

  def edit
    find_blog_post
  end

  def update
    fix_published_at_timezone
    find_blog_post
    if @blog_post.update(params[:blog_post])
      flash[:success] = "Blog Post updated."
      redirect_to @blog_post
    else
      render :edit
    end
  end

  def destroy
    find_blog_post
    @blog_post.destroy!
    flash[:success] = "Blog post \"#{@blog_post.title}\" destroyed."
    redirect_to blog_posts_path
  end

  private

  def find_blog_post
    if admin?
      @blog_post = BlogPost.find(params[:id])
    else
      @blog_post = BlogPost.published.find(params[:id])
    end
  end

  def fix_published_at_timezone
    Rails.logger.debug "params[:blog_post][:published_at]: #{params[:blog_post][:published_at]}"
    if params[:blog_post][:published_at].present?
      Time.zone = "Eastern Time (US & Canada)"
      params[:blog_post][:published_at] = Time.zone.parse(params[:blog_post][:published_at])
      Rails.logger.debug "params[:blog_post][:published_at]: #{params[:blog_post][:published_at]}"
    end
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
  def blog_post_preview_image_tag(blog_post)
    return if blog_post.content.blank?

    doc = Nokogiri::HTML(blog_post.content)
    first_img_src = doc.css('img').first&.attr('src')

    return unless first_img_src.present?

    link_to blog_post do
      image_tag(first_img_src, style: "float: right; max-width: 200px; max-height: 98px; margin: 0 5px 5px;")
    end
  end
end

app/views/blog_posts/_blog_post.html.erb
<% truncated = false if local_assigns[:truncated].nil? %>

<%= link_to blog_post do %>
  <h1 style="text-align: left; color: black; margin-bottom: 10px; font-size: 2.2em;">
    <%= sanitize blog_post.title %>
  </h1>
<% end %>

<p style="opacity: 0.8; font-size: 90%;">
  <%= blog_post.published_at_string %>

  <% if admin? %>
    - <%= link_to "Edit post", edit_blog_post_path(blog_post) %>
    / <%= link_to "Delete post", blog_post_path(blog_post), method: :delete,
      data: { confirm: "Really delete this blog post now and forever?" }
    %>
  <% end %>

  <% if blog_post.topic_list.present? %>
    <br />
    Topics: <%= blog_post.topic_list %>
  <% end %>
</p>

<div class="blog-post-content">
  <% if truncated %>
    <%= blog_post_preview_image_tag(blog_post) %>

    <%= link_to blog_post, style: "color: black; text-decoration: none;" do %>
      <%= truncate(strip_tags(blog_post.content), length: 450) do %>
        <%= link_to "Keep reading", blog_post %>
      <% end %>
    <% end %>
  <% else %>
    <%= blog_post.content.html_safe %>
  <% end %>
</div>

<br />

app/views/blog_posts/_fields.html.erb
<%= f.label :title %>
<%= f.text_field :title %>
<p class="form-help">The blog post's title. (The URL slug will be auto-generated from it.)</p>

<%= f.label :content %>
<%= f.text_area :content, id: 'blog_post_content', rows: 50 %>
<p class="form-help">Content/body of the post.</p>

<%= f.label :topic_list, "Topics" %>
<%= f.text_field :topic_list, value: f.object.topic_list.join(", ") %>
<p class="form-help">Topics that this post deals with, comma-separated. The category options are: #SGJ202X, education, game development, science, playing</p>

<%= f.label :published_at %>
<%= f.datetime_local_field :published_at %>
<p class="form-help">When this post was/will be published, in Eastern Time (US & Canada). Set it to now or the past to make it visible to all site visitors. Set it to the future to schedule future publishing. Make it blank to keep it hidden to regular site visitors.</p>

<%= f.label :pinned, "#{f.check_box :pinned} Pinned".html_safe %>
<p class="form-help">Check this to pin this post to the top of the homepage.</p>

<%= f.label :use_as_game_jam_page, "#{f.check_box :use_as_game_jam_page} Use as Game Jam page".html_safe %>
<p class="form-help">If checked, the Game Jam links and the /jam URL will redirect to this post. If enabled for multiple posts, it will use the most recently published one.</p>

<%# Set up WYSIWYG editor, TinyMCE %>
<script src="/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
<script>
  console.log("Setting up TinyMCE editor...")
  tinymce.init({
    selector: '#blog_post_content',
    plugins: 'lists code link hr codesample image',
    menubar: false,
    toolbar: 'undo redo | styles | bold italic | link image | blockquote codesample hr | bullist numlist | code'
  });
</script>

app/views/blog_posts/_pinned_and_unpinned_posts.html.erb
<% if @pinned_blog_posts.present? %>
  <div class="pinned-blog-post" style="padding: 20px 20px 5px; border: 1px solid #ddd; border-radius: 5px;">
    <%= render partial: 'blog_posts/blog_post', collection: @pinned_blog_posts, locals: { truncated: true } %>
  </div>
  <br />
<% end %>

<%= render partial: 'blog_posts/blog_post', collection: @blog_posts, locals: { truncated: true } %>

app/views/blog_posts/_topics_filter.html.erb
<p style="margin-bottom: 0;">Show Posts About...</p>

<%# based on games filters with minimal changes %>
<% categories_array = [["topic", "Topics"]] %>

<% topic_names = BlogPost.topic_counts.select { |t| t.taggings_count > 0 }.map(&:name) %>

<% categories_array.each do |s, f| %>
<div id="<%=s%>_dropdown">
<%= select :blog_post, s, topic_names, {include_blank: "All Post #{f}"} %>
</div>
<% end %>

<script>
$(document).ready(function() {
  <% params_without_page = params.except(:page, :action, :controller) %>
  <% (categories_array).each do |s, f| %>
    <% if params_without_page[s] %>
      $('#blog_post_<%=s%>').val("<%= params_without_page[s] %>");
    <% end %>
    $('#blog_post_<%=s%>').bind('change', function(event) {
      if (event.target.value) {
        <% if params_without_page.count > 2 %>
          window.location.href = "<%= raw (!params_without_page[s].blank? && params_without_page.count == 3) ? blog_posts_path(params_without_page.merge(s => nil))+"?#{s}=" : blog_posts_path(params_without_page.merge(s => nil))+"&#{s}=" %>"+event.target.value;
        <% else %>
          window.location.href = "<%= raw blog_posts_path()+"?#{s}=" %>"+event.target.value;
        <% end %>
      } else {
        window.location.href = "<%= raw blog_posts_path(params_without_page.merge(s => nil)) %>";
      }
    });
  <% end %>
});
</script>

app/views/blog_posts/edit.html.erb
<%= provide(:title, 'Edit blog post') %>

<h1>Edit blog post</h1>

<div class="row">
  <div class="span8 offset1">

    <%= form_for(@blog_post) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= render 'blog_posts/fields', f: f %>

      <p class="form-help" id="submit-help"><b>Be aware:</b> Upon saving, this blog post will immediately be visible if "Published at" is set to now or the past above.</p>
      <%= f.submit "Update blog post", :class => "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

app/views/blog_posts/index.html.erb
<%
  if @topic.present?
    title = "#{@topic.titleize} Blog Posts"
  else
    title = "All Blog Posts"
  end
%>

<% provide(:title, title) %>

<h1><%= title %></h1>

<% if admin? %>
  <p style="text-align: center;"><%= link_to "New blog post", new_blog_post_path, class: 'btn btn-info'  %></p>
  <br />
<% end %>

<div class="blog_posts">
  <%= render partial: 'blog_posts/pinned_and_unpinned_posts' %>
</div>

<% if @pinned_blog_posts.size < 1 && @blog_posts.size < 1 %>
  <p>No blog posts matching that criteria were found. <%= link_to "View all blog posts.", blog_posts_path %></p>
<% end %>

<%= will_paginate %>

app/views/blog_posts/new.html.erb
<%= provide(:title, 'New blog post') %>

<h1>New blog post</h1>

<div class="row">
  <div class="span8 offset1">

    <%= form_for(@blog_post) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= render 'blog_posts/fields', f: f %>

      <p class="form-help" id="submit-help"><b>Be aware:</b> Upon saving, this blog post will immediately be visible if "Published at" is set to now or the past above.</p>
      <%= f.submit "Create blog post", :class => "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

app/views/blog_posts/show.html.erb
<% provide(:title, @blog_post.title) %>

<%= render 'blog_posts/blog_post', blog_post: @blog_post %>

<%= render 'layouts/share_buttons', not_floaty: true %>
<br />

<%= link_to "Back to Blog", blog_posts_path %>