config/routes.rb
SciencegamereviewsOrg::Application.routes.draw do

  constraints host: 'sciencegamecenter.org' do
    get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
  end

  root :to => 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'
  get '/review', to: 'static_pages#review'
  get '/jam', to: 'static_pages#jam'
  get '/forum_approval', to: 'static_pages#forum_approval'
  get '/robots.txt', to: 'static_pages#robots'

  resources :users do
    member do
      get 'resend_parent_email'
      get 'confirm_child_account'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :games do
    resources :screenshots, shallow: true
  end
  resources :subjects, only: :index
  resources :platforms, only: :index
  resources :player_reviews
  resources :comments
  resources :blog_posts

  resources :stats, only: :index

  post "versions/:id/revert" => "versions#revert", as: 'revert_version'

  get '/signup',  to: 'users#new'
  get '/login',   to: 'sessions#new'
  delete '/logout',  to: 'sessions#destroy'

  get '/sso/discourse', to: 'sso#discourse'











end

app/models/game.rb
require 'csv'

class Game < ActiveRecord::Base
  attr_accessible :title, :description, :website_url, :developer,
  								:intended_audience, :concepts, :disabled,
  								:boxart, :youtube_video_url,
                  :platform_list, :subject_list,
  								:cost_list, :intended_for_list, :developer_type_list,
                                :teacher_info, :entertainment

  default_scope { order('games.updated_at DESC, games.title ASC') }
  scope :enabled, -> { where(disabled: false) }
  scope :disabled, -> { where(disabled: true) }

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  has_many :player_reviews, dependent: :destroy
  has_many :screenshots,		dependent: :destroy

  has_paper_trail

  acts_as_taggable_on :subjects, :platforms, :costs, :intended_fors, :developer_types

  has_attached_file :boxart,
  									styles: {
  										large: '500x500>',
  										medium: '300x300>',
  										small: '100x100>',
  										thumb: '100x100#',
  										banner: '2000x90#'
  									},
  									convert_options: { banner: "-blur 0x8" },
  									storage: :s3,
  									s3_credentials: S3_CREDENTIALS,
  									s3_protocol: :https,
  									default_url: 'no_box.png'

  validates :title,	presence: true
  validates_attachment :boxart, content_type: {
  										 content_type: ['image/jpeg', 'image/png', 'image/gif'] }

  def self.chart_data(start = 3.weeks.ago) #TODO: Make this not run a query for each date
    (start.to_date..Date.today).map do |date|
    	if (date == start.to_date) || (date == Date.today) || (Game.where(["date(created_at) = ?", date]).count > 0)
      {
        created_at: date,
        enabled_count: Game.enabled.where(["date(created_at) <= ?", date]).count,
        disabled_count: Game.disabled.where(["date(created_at) <= ?", date]).count
      }
    	else
    	{
        created_at: date,
      }
   		end
    end
  end

  def actual_player_reviews
  	reviews = []
  	self.player_reviews.each do |r|
  		reviews += [r] if r.user && !r.user.is_expert? && !r.user.is_authoritative?
  	end
  	reviews
  end

  def authoritative_reviews
  	reviews = []
  	self.player_reviews.each do |r|
  		reviews += [r] if r.user && r.user.is_authoritative?
  	end
  	reviews
  end

  def expert_reviews
  	reviews = []
  	self.player_reviews.each do |r|
  		reviews += [r] if r.user && r.user.is_expert? && !r.user.is_authoritative?
  	end
  	reviews
  end

  def teacher_reviews
  	reviews = []
  	self.player_reviews.each do |r|
  		reviews += [r] if r.user && r.user.is_teacher?
  	end
  	reviews
  end

  def scientist_reviews
  	reviews = []
  	self.player_reviews.each do |r|
  		reviews += [r] if r.user.is_scientist?
  	end
  	reviews
  end

  def game_developer_reviews
  	reviews = []
  	self.player_reviews.each do |r|
  		reviews += [r] if r.user.is_game_developer?
  	end
  	reviews
  end

# PLAYER AVERAGES
	def player_fun_average(round = true)
		if self.approved_player_reviews_count < 1
			-1
		elsif @player_fun_rating_average
			round ? @player_fun_rating_average.round(1) : @player_fun_rating_average
		else
			total = 0
			count = 0
			self.player_reviews.each do |r|
				total += r.fun_rating.to_f if r.approved?
				count += 1 if r.approved?
			end
			@player_fun_rating_average = total / count
			round ? @player_fun_rating_average.round(1) : @player_fun_rating_average
		end
	end

	def player_accuracy_average(round = true)
		if self.approved_player_reviews_count < 1
			-1
		elsif @player_accuracy_rating_average
			round ? @player_accuracy_rating_average.round(1) : @player_accuracy_rating_average
		else
			total = 0
			count = 0
			self.player_reviews.each do |r|
				total += r.accuracy_rating.to_f if r.approved?
				count += 1 if r.approved?
			end
			@player_accuracy_rating_average = total / count
			round ? @player_accuracy_rating_average.round(1) : @player_accuracy_rating_average
		end
	end

	def player_effectiveness_average(round = true)
		if self.approved_player_reviews_count < 1
			-1
		elsif @player_effectiveness_rating_average
			round ? @player_effectiveness_rating_average.round(1) : @player_effectiveness_rating_average
		else
			total = 0
			count = 0
			self.player_reviews.each do |r|
				total += r.effectiveness_rating.to_f if r.approved?
				count += 1 if r.approved?
			end
			@player_effectiveness_rating_average = total / count
			round ? @player_effectiveness_rating_average.round(1) : @player_effectiveness_rating_average
		end
	end

	def player_averages_total
    @player_rating_averages_total ||= player_averages_total_uncached
	end

  def player_averages_total_uncached
    if self.approved_player_reviews_count < 1
      return -1
    else
      player_rating_averages_total =
        player_fun_average(false) +
        player_accuracy_average(false) +
        player_effectiveness_average(false)

      return player_rating_averages_total.round(1)
    end
  end

	def approved_player_reviews_count
		count = 0
		unless self.player_reviews.nil?
			self.player_reviews.each do |r|
				count += 1 if r.approved?
			end
		end
		count
	end

# EXPERT AVERAGES
	def expert_fun_average(round = true)
		if self.approved_expert_reviews_count < 1
			-1
		elsif @expert_fun_rating_average
			round ? @expert_fun_rating_average.round(1) : @expert_fun_rating_average
		else
			total = 0
			count = 0
			self.expert_reviews.each do |r|
				total += r.fun_rating.to_f if r.approved?
				count += 1 if r.approved?
			end
			@expert_fun_rating_average = total / count
			round ? @expert_fun_rating_average.round(1) : @expert_fun_rating_average
		end
	end

	def expert_accuracy_average(round = true)
		if self.approved_expert_reviews_count < 1
			-1
		elsif @expert_accuracy_rating_average
			round ? @expert_accuracy_rating_average.round(1) : @expert_accuracy_rating_average
		else
			total = 0
			count = 0
			self.expert_reviews.each do |r|
				total += r.accuracy_rating.to_f if r.approved?
				count += 1 if r.approved?
			end
			@expert_accuracy_rating_average = total / count
			round ? @expert_accuracy_rating_average.round(1) : @expert_accuracy_rating_average
		end
	end

	def expert_effectiveness_average(round = true)
		if self.approved_expert_reviews_count < 1
			-1
		elsif @expert_effectiveness_rating_average
			round ? @expert_effectiveness_rating_average.round(1) : @expert_effectiveness_rating_average
		else
			total = 0
			count = 0
			self.expert_reviews.each do |r|
				total += r.effectiveness_rating.to_f if r.approved?
				count += 1 if r.approved?
			end
			@expert_effectiveness_rating_average = total / count
			round ? @expert_effectiveness_rating_average.round(1) : @expert_effectiveness_rating_average
		end
	end

	def expert_averages_total
		if self.approved_expert_reviews_count < 1
			-1
		elsif @expert_rating_averages_total
			@expert_rating_averages_total.round(1)
		else
			@expert_rating_averages_total =
				expert_fun_average(false) +
				expert_accuracy_average(false) +
				expert_effectiveness_average(false)
			@expert_rating_averages_total.round(1)
		end
	end

	def approved_expert_reviews_count
		count = 0
		unless self.expert_reviews.nil?
			self.expert_reviews.each do |r|
				count += 1 if r.approved?
			end
		end
		count
	end

# AUTHORITATIVE AVERAGES
	def authoritative_fun_average(round = true)
		if self.approved_authoritative_reviews_count < 1
			-1
		elsif @authoritative_fun_rating_average
			round ? @authoritative_fun_rating_average.round(1) : @authoritative_fun_rating_average
		else
			total = 0
			count = 0
			self.authoritative_reviews.each do |r|
				total += r.fun_rating.to_f if r.approved?
				count += 1 if r.approved?
			end
			@authoritative_fun_rating_average = total / count
			round ? @authoritative_fun_rating_average.round(1) : @authoritative_fun_rating_average
		end
	end

	def authoritative_accuracy_average(round = true)
		if self.approved_authoritative_reviews_count < 1
			-1
		elsif @authoritative_accuracy_rating_average
			round ? @authoritative_accuracy_rating_average.round(1) : @authoritative_accuracy_rating_average
		else
			total = 0
			count = 0
			self.authoritative_reviews.each do |r|
				total += r.accuracy_rating.to_f if r.approved?
				count += 1 if r.approved?
			end
			@authoritative_accuracy_rating_average = total / count
			round ? @authoritative_accuracy_rating_average.round(1) : @authoritative_accuracy_rating_average
		end
	end

	def authoritative_effectiveness_average(round = true)
		if self.approved_authoritative_reviews_count < 1
			-1
		elsif @authoritative_effectiveness_rating_average
			round ? @authoritative_effectiveness_rating_average.round(1) : @authoritative_effectiveness_rating_average
		else
			total = 0
			count = 0
			self.authoritative_reviews.each do |r|
				total += r.effectiveness_rating.to_f if r.approved?
				count += 1 if r.approved?
			end
			@authoritative_effectiveness_rating_average = total / count
			round ? @authoritative_effectiveness_rating_average.round(1) : @authoritative_effectiveness_rating_average
		end
	end

	def authoritative_averages_total
		if self.approved_authoritative_reviews_count < 1
			-1
		elsif @authoritative_rating_averages_total
			@authoritative_rating_averages_total.round(1)
		else
			@authoritative_rating_averages_total =
				authoritative_fun_average(false) +
				authoritative_accuracy_average(false) +
				authoritative_effectiveness_average(false)
			@authoritative_rating_averages_total.round(1)
		end
	end

	def approved_authoritative_reviews_count
		count = 0
		unless self.authoritative_reviews.nil?
			self.authoritative_reviews.each do |r|
				count += 1 if r.approved?
			end
		end
		count
	end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      attrs = %w( title website_url developer subject_list concepts )
      csv << attrs
      all.each do |game|
        csv << attrs.map{|a| game.send(a)}
      end
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_filter :signed_in_user,  except: [:index, :show]
  before_filter :admin_user,      except: [:index, :show, :new, :create]

  def index
    get_page_of_games

    respond_to do |format|
      format.html
      format.csv { send_data @games.to_csv }
    end
  end

  def show
    @game = Game.find(params[:id])

    if @game.disabled? && !admin?
      flash[:failure] = "Swiper, no swiping! Sorry, you aren't able to view that page unless you're a site administrator."
      redirect_to root_path
    end

    @player_reviews = @game.actual_player_reviews
    @expert_reviews = @game.expert_reviews
    @authoritative_reviews = @game.authoritative_reviews
    @player_review = PlayerReview.new

    if request.path != game_path(@game)
      redirect_to @game, status: :moved_permanently
    end
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(params[:game])
    if @game.save
      if admin?
        flash[:success] = "Game #{@game.title} created."
        redirect_to @game
      else
        GameMailer.notify_of_new_game(@game, current_user).deliver_now
        flash[:success] = view_context.sanitize "Your game <i>#{@game.title}</i> has been submitted and will be considered by the SGC Team. Thanks!"
        redirect_to games_path
      end
    else
      render 'new'
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update_attributes(params[:game])
      flash[:success] = view_context.sanitize "Game <i>#{@game.title}</i> updated."
      redirect_to @game
    else
      render 'edit'
    end
  end

  def destroy
    game = Game.find(params[:id])
    Game.find(params[:id]).destroy
    flash[:success] = view_context.sanitize "Game <i>#{game.title}</i> and all its reviews and comments have been destroyed now and forever."
    redirect_to games_path
  end
end

app/helpers/games_helper.rb
module GamesHelper

	def platform_links_list(game = @game)
		if game && game.platforms
			game.platforms.sort_by { |t| GAME_PLATFORMS.index(t.name) || -1 }.collect {|t| link_to(t.name, games_path(platform: t.name), title: "See all games available for #{t.name}") }.join(" // ").html_safe
		end
	end

	def subject_links_list(game = @game)
		if game && game.subjects
			game.subjects.sort_by { |t| GAME_SUBJECTS.index(t.name) || -1 }.collect {|t| link_to(t.name, games_path(subject: t.name), title: "See all games that deal with #{t.name}") }.join(" // ").html_safe
		end
	end

	def intended_for_links_list(game = @game)
		if game && game.intended_fors
			game.intended_fors.sort_by { |t| GAME_INTENDED_FORS.index(t.name) || -1 }.collect {|t| link_to(t.name, games_path(intended_for: t.name), title: "See all games intended for #{t.name}") }.join(" // ").html_safe
		end
	end

	def developer_type_links_list(game = @game)
		if game && game.developer_types
			game.developer_types.sort_by { |t| GAME_DEVELOPER_TYPES.index(t.name) || -1 }.collect {|t| link_to(t.name, games_path(developer_type: t.name), title: "See all games by a #{t.name}") }.join(" // ").html_safe
		end
	end

	def cost_links_list(game = @game)
		if game && game.costs
			game.costs.sort_by { |t| GAME_COSTS.index(t.name) || -1 }.collect {|t| link_to(t.name, games_path(cost: t.name), title: "See all #{t.name} games") }.join(" // ").html_safe
		end
	end

	def random_screenshot_image(game = @game)
		if (c = game.screenshots.count) != 0
      game.screenshots.offset(rand(c)).first.image
    else
    	game.boxart
		end
	end

	def youtube_embed_iframe(url)
		if url.present?
			url_params = Rack::Utils.parse_nested_query(url.split('?').last)
	    youtube_id = url_params["v"]
	    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}", frameBorder: 0)
		end
	end
end

app/views/games/_admin_tools.html.erb
<p>
				<b><%= link_to "Edit game", edit_game_path(game) %></b> // 
				<%= link_to "Manage screenshots", game_screenshots_path(game) %>
</p>

app/views/games/_new_game_button.html.erb
        <% if admin? %>
        <hr />
        <p><%= link_to "New game", new_game_path, class: 'btn btn-info'  %></p>
        <% else %>
        <hr />
        <p><%= link_to "Suggest a game", new_game_path, class: 'btn btn-info' %></p>
        <% end %>

app/views/games/_new_player_review.html.erb
<%= form_for @player_review, url: player_reviews_path(method: :post, anchor: :new_player_review) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= render 'player_reviews/fields', f: f %>

      <%= f.hidden_field :game_id, value: @game.id %>

      <p class="form-help" id="submit-help">After submitting, a site administrator will need to approve your review before it shows up. We're usually pretty prompt about it.</p>
      <%= f.submit "Submit review", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/games/_scorecard.html.erb
<hr />
<div class="row" id="scorecards"><div class="span12">

<h2>Scorecards</h2>

<div class="row">

<!-- AUTHORITATIVE -->
<!--
<div class="span3"><table class="table table-bordered">
<thead>
<tr>
	<th colspan="2"><strong><%= link_to "SGC Reviews", game_path(@game, anchor: 'authoritative_reviews') %></strong><br/>
		Our official reviews</th>

	<% if game.authoritative_averages_total >= 0 %>
	<th class="score_total_cell">
		<span class="score_total"><%= game.authoritative_averages_total.round(0) %></span><small> / 15</small></span>
	</th>
	<% else %>
	<th>&mdash;</th>
	<% end %>

</tr>
</thead>
<% if game.authoritative_averages_total >= 0 %>
<tbody>
<tr>
	<th width="30px"><%= t('review.fun') %></th>
	<td width="*%">
		<div class="progress <%= progress_color(game.authoritative_fun_average) %>">
			<div class="bar" style="width: <%= game.authoritative_fun_average * 20 %>%;"></div>
		</div>
	</td>
	<td width="30px">
		<b><%= game.authoritative_fun_average.round(0) %></b> <small> / 5</small>
	</td>
</tr>
<tr>
	<th><%= t('review.learning') %></th>
	<td width="*%">
		<div class="progress <%= progress_color(game.authoritative_effectiveness_average) %>">
			<div class="bar" style="width: <%= game.authoritative_effectiveness_average * 20 %>%;"></div>
		</div>
	</td>
	<td>
		<b><%= game.authoritative_effectiveness_average.round(0) %></b> <small> / 5</small>
	</td>
</tr>
<tr>
	<th><%= t('review.science') %></th>
	<td width="*%">
		<div class="progress <%= progress_color(game.authoritative_accuracy_average) %>">
			<div class="bar" style="width: <%= game.authoritative_accuracy_average * 20 %>%;"></div>
		</div>
	</td>
	<td>
		<b><%= game.authoritative_accuracy_average.round(0) %></b> <small> / 5</small>
	</td>
</tr>
</tbody>
<% else %>
<tbody>
<tr>
	<td colspan="3" rowspan="3">
		We haven't published our official SGC review(s) of <i><%= @game.title %></i> quite yet.
	</td>
</tr>
</tbody>
<% end %>

</table>
</div>
-->

<!-- EXPERT -->
<div class="span5"><table class="table table-bordered">
<thead>
<tr>
	<th colspan="2"><strong><%= link_to "Expert Reviews", game_path(@game, anchor: 'expert_reviews') %></strong><br/>
		By scientists and teachers</th>

	<% if game.expert_averages_total >= 0 %>
	<th class="score_total_cell">
		<span class="score_total"><%= game.expert_averages_total.round(0) %></span><small> / 15</small></span>
	</th>
	<% else %>
	<th>&mdash;</th>
	<% end %>

</tr>
</thead>
<% if game.expert_averages_total.round(0) >= 0 %>
<tbody>
<tr>
	<th width="30px"><%= t('review.fun') %></th>
	<td width="*%">
		<div class="progress <%= progress_color(game.expert_fun_average) %>">
			<div class="bar" style="width: <%= game.expert_fun_average * 20 %>%;"></div>
		</div>
	</td>
	<td width="30px">
		<b><%= game.expert_fun_average.round(0) %></b> <small> / 5</small>
	</td>
</tr>
<tr>
	<th><%= t('review.learning') %></th>
	<td width="*%">
		<div class="progress <%= progress_color(game.expert_effectiveness_average) %>">
			<div class="bar" style="width: <%= game.expert_effectiveness_average * 20 %>%;"></div>
		</div>
	</td>
	<td>
		<b><%= game.expert_effectiveness_average.round(0) %></b> <small> / 5</small>
	</td>
</tr>
<tr>
	<th><%= t('review.science') %></th>
	<td width="*%">
		<div class="progress <%= progress_color(game.expert_accuracy_average) %>">
			<div class="bar" style="width: <%= game.expert_accuracy_average * 20 %>%;"></div>
		</div>
	</td>
	<td>
		<b><%= game.expert_accuracy_average.round(0) %></b> <small> / 5</small>
	</td>
</tr>
</tbody>
<% else %>
<tbody>
<tr>
	<td colspan="3" rowspan="3">
		We don't have any expert reviews yet for <i><%= @game.title %></i>.<br />
		Are you a scientist who has played this game or a teacher who has used it in the classroom? <%= link_to "Contact us about writing an expert review today.", contact_path %>
	</td>
</tr>
</tbody>
<% end %>

</table>
</div>

<!-- PLAYER -->
<div class="span5"><table class="table table-bordered">
<thead>
<tr>
	<th colspan="2"><strong><%= link_to "Player Reviews", game_path(@game, anchor: 'player_reviews') %></strong><br/>
		By everyone else (and you!)</th>

	<% if game.player_averages_total >= 0 %>
	<th class="score_total_cell">
		<span class="score_total"><%= game.player_averages_total.round(0) %></span><small> / 15</small></span>
	</th>
	<% else %>
	<th>&mdash;</th>
	<% end %>

</tr>
</thead>
<% if game.player_averages_total >= 0 %>
<tbody>
<tr>
	<th width="50px"><%= t('review.fun') %></th>
	<td width="*%">
		<div class="progress <%= progress_color(game.player_fun_average) %>">
			<div class="bar" style="width: <%= game.player_fun_average * 20 %>%;"></div>
		</div>
	</td>
	<td width="30px">
		<b><%= game.player_fun_average.round(0) %></b> <small> / 5</small>
	</td>
</tr>
<tr>
	<th><%= t('review.learning') %></th>
	<td width="*%">
		<div class="progress <%= progress_color(game.player_effectiveness_average) %>">
			<div class="bar" style="width: <%= game.player_effectiveness_average * 20 %>%;"></div>
		</div>
	</td>
	<td>
		<b><%= game.player_effectiveness_average.round(0) %></b> <small> / 5</small>
	</td>
</tr>
<tr>
	<th><%= t('review.science') %></th>
	<td width="*%">
		<div class="progress <%= progress_color(game.player_accuracy_average) %>">
			<div class="bar" style="width: <%= game.player_accuracy_average * 20 %>%;"></div>
		</div>
	</td>
	<td>
		<b><%= game.player_accuracy_average.round(0) %></b> <small> / 5</small>
	</td>
</tr>
</tbody>
<% else %>
<tbody>
<tr>
	<td colspan="3" rowspan="3">
		No players have left any reviews yet for <i><%= @game.title %></i>.<br />
		Have you played this game? <%= link_to "Share your experience below!", game_path(@game, anchor: 'new_player_review') %>
	</td>
</tr>
</tbody>
<% end %>

</table>


</div>

</div>

</div></div>

app/views/games/edit.html.erb
<% provide(:title, "Edit game") %>
<h1>Edit game</h1>

<div class="row">
  <div class="span6 offset2">

    <%= form_for @game, :html => { :multipart => true } do |f| %>

    	<%= render 'shared/error_messages', object: f.object %>

      <%= render 'games/fields', f: f %>

      <p class="form-help" id="submit-help"><b>Be aware:</b> Upon saving, any changes will immediately be visible on the site unless <b>Disabled</b> is checked above (in which the game won't be visible at all).</p>
      <%= f.submit "Update game", :class => "btn btn-large btn-primary" %>

    <% end %>

    <p>
      <%= link_to "Delete game", @game, method: :delete, data: { confirm: "Are you sure you want to destroy this game now and for the rest of time, with no going back?" } %>
    </p>

    <p><%= link_to "Manage this game's screenshots", game_screenshots_path(@game) %></p>
  </div>
</div>

app/views/games/show.html.erb
<%= provide(:title, @game.title) %>
<!--
<ul class="breadcrumb">
	<li>
		<%= link_to "Games", games_path %> <span class="divider">&raquo;</span>
	</li>
	<li>
		<i><%= @game.title %></i>
	</li>
</ul>
-->
<div class="row">
	<div class="span4 game-info">
		<%= tracked_link_to image_tag(@game.boxart.url(:medium), class: :boxart, alt: @game.title), @game.website_url, title: "Visit this game's website", target: '_blank', rel: 'noopener' %>
		<br />
		<%= render 'games/game_info', game: @game %>
		<center><%= tracked_link_to 'Play this game!<br /><small>on its own website</small>'.html_safe, @game.website_url, class: "btn btn-large btn-success", style: "margin: 5px", target: "_blank" %></center>
		<% if signed_in? && current_user.is_admin? %>
		<hr />
		<div style="margin-left: 5px; margin-top: 10px;"><%= render 'games/admin_tools', game: @game %></div>
		<% end %>
	</div>

	<div class="span6" style="max-width: 459px;">
		<h1 class="left"><i><%= @game.title %></i></h1>
		<% if admin? && @game.disabled? %>
			<div class="alert">
				<strong>Disabled.</strong> This game is hidden from public view. Edit it to enable.
			</div>
		<% end %>
		<% if @game.entertainment? %>
		<div class="entertainment">
			<p><i><b>Primarily for entertainment:</b> This game is not intended to teach, but rather to simply raise awareness and interest in a scientific concept.</i>
		</div>
		<% end %>
		<div class="description">
			<%= markdown @game.description %>
		</div>
		<br />
	</div>

</div>

<style>
	#top_banners_wrapper {
		background: #d3d3d3 url('<%= random_screenshot_image(@game).url(:banner) %>') repeat center !important;
		background-size: cover;
	}
</style>

<%= render 'games/video' %>

<%= render 'games/screenshots' if @game.screenshots.count > 0 %>

<%= render 'games/scorecard', game: @game %>

<% if @authoritative_reviews.present? %>
	<div id="authoritative_reviews">
		<hr />
		<h2 class="left">Official SGC Reviews</h2>
		<% @authoritative_reviews.each do |review| %>
			<% if review.approved? || (review.pending? && signed_in? && current_user?(review.user)) || signed_in? && admin? %>
				<%= render 'player_reviews/player_review', review: review %>
				<hr />
			<% end %>
		<% end %>
	</div>
<% end %>

<% if @expert_reviews.present? %>
	<div id="expert_reviews">
		<h2 class="left">Expert Reviews</h2>
		<% @expert_reviews.each do |review| %>
			<% if review.approved? || (review.pending? && signed_in? && current_user?(review.user)) || signed_in? && admin? %>
				<%= render 'player_reviews/player_review', review: review %>
				<hr />
			<% end %>
		<% end %>
	</div>
<% end %>

<% if @player_reviews.present? %>
	<div id="player_reviews">
		<h2 class="left">Player Reviews</h2>
		<% @player_reviews.each do |review| %>
			<% if review.approved? || (review.pending? && signed_in? && current_user?(review.user)) || signed_in? && admin? %>
				<%= render 'player_reviews/player_review', review: review %>
				<hr />
			<% end %>
		<% end %>
	</div>
<% end %>

<h3>Leave a review</h3>
<% if signed_in? && @game.player_reviews.where(user_id: @current_user.id).count < 1 %>
<div class="row" id="new_player_review">
  <div class="span10">

    <div class="form-description">
      <p>Have you played this game? Share your experience by leaving a review!</p>
    </div>

    <%= avatar_for @current_user %>
    <p>
	    <b><%= @current_user.name %></b><br />
	    <%= @current_user.roles %>
  	</p>
  	<br />

    <%= render 'games/new_player_review', player_review: @player_review %>

  </div>
</div>
<% elsif signed_in? %>
<div class="row" id="new_player_review">
  <div class="span10">
		<p>Thanks for reviewing! You can only review each game once. If you'd like, you are welcome to edit your existing review above.</p>
	</div>
</div>
<% else %>
<div class="row" id="new_player_review">
  <div class="span10">
		<p><%= link_to "Sign up", signup_path %> or <%= link_to "log in", login_path %> to post a review of your own!</p>
	</div>
</div>
<% end %>

<br />
<%= render partial: 'layouts/site_name_and_big_nav_buttons' %>